CFLAGS_blu_plug.o := -Wno-unused-function \

CFLAGS_msm_zen_decision.o := -Wno-unused-function \

CFLAGS_alucard_hotplug.o := -Wno-unused-function -Wno-unused-variable -Wno-pointer-to-int-cast
					
obj-$(CONFIG_INTELLI_HOTPLUG) += intelli_hotplug.o
obj-$(CONFIG_ASMP)	      += autosmp.o
obj-$(CONFIG_BRICKED_HOTPLUG) += bricked_hotplug.o
obj-$(CONFIG_ALUCARD_HOTPLUG) += alucard_hotplug.o
obj-$(CONFIG_BLU_PLUG) += blu_plug.o
obj-$(CONFIG_ZEN_DECISION) += msm_zen_decision.o
obj-$(CONFIG_MAKO_HOTPLUG)    += mako_hotplug.o

