obj-$(CONFIG_INTELLI_HOTPLUG) += intelli_hotplug.o
obj-$(CONFIG_ASMP)	      += autosmp.o
obj-$(CONFIG_BRICKED_HOTPLUG) += bricked_hotplug.o
obj-$(CONFIG_ALUCARD_HOTPLUG) += alucard_hotplug.o
obj-$(CONFIG_BLU_PLUG) += blu_plug.o

